apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deplo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: my-nodejs-ctr
        image: gchaudhari/mynodejs